---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - finops.infercost.ai
  resources:
  - costprofiles
  - usagereports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - finops.infercost.ai
  resources:
  - costprofiles/finalizers
  - usagereports/finalizers
  verbs:
  - update
- apiGroups:
  - finops.infercost.ai
  resources:
  - costprofiles/status
  - usagereports/status
  verbs:
  - get
  - patch
  - update
