apiVersion: finops.infercost.ai/v1alpha1
kind: UsageReport
metadata:
  labels:
    app.kubernetes.io/name: infercost
    app.kubernetes.io/managed-by: kustomize
  name: daily-report
spec:
  costProfileRef: gpu-cluster-example
  schedule: daily
