apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "infercost.fullname" . }}-controller-manager
  namespace: {{ include "infercost.namespace" . }}
  labels:
    {{- include "infercost.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.controllerManager.replicaCount }}
  selector:
    matchLabels:
      {{- include "infercost.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "infercost.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "infercost.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.controllerManager.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        image: {{ include "infercost.controllerImage" . }}
        imagePullPolicy: {{ .Values.controllerManager.image.pullPolicy }}
        command:
        - /manager
        args:
        {{- if .Values.controllerManager.leaderElection.enabled }}
        - --leader-elect
        {{- end }}
        - --health-probe-bind-address=:8081
        {{- if .Values.metrics.enabled }}
        - --metrics-bind-address=:{{ .Values.metrics.service.port }}
        - --metrics-secure={{ .Values.metrics.secure }}
        {{- end }}
        {{- if .Values.dcgm.endpoint }}
        - --dcgm-endpoint={{ .Values.dcgm.endpoint }}
        {{- end }}
        {{- if .Values.api.enabled }}
        - --api-bind-address=:{{ .Values.api.port }}
        {{- end }}
        ports:
        - name: health
          containerPort: 8081
          protocol: TCP
        {{- if .Values.metrics.enabled }}
        - name: metrics
          containerPort: {{ .Values.metrics.service.port }}
          protocol: TCP
        {{- end }}
        {{- if .Values.api.enabled }}
        - name: api
          containerPort: {{ .Values.api.port }}
          protocol: TCP
        {{- end }}
        {{- with .Values.controllerManager.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          {{- toYaml .Values.controllerManager.securityContext | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.controllerManager.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.controllerManager.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.controllerManager.resources | nindent 10 }}
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      {{- with .Values.controllerManager.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.controllerManager.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
